language: csharp
solution: TravisCI.sln
branches:https://github.com/sanjaya4491/TravisCI.git
  only:
  - master
install:
  - nuget restore TravisCI.sln
script:
  - msbuild /p:Configuration=Release TravisCI.sln